services:
  db:
    image: postgres:alpine
    env_file:
      - ../.env
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    deploy:
      resources:
        limits:
          memory: 256m

  valkey:
    image: valkey/valkey:alpine
    container_name: tangerine_api_valkey
    restart: always
    command: >
      valkey-server
      --port ${REDIS_PORT}
      --maxmemory 200mb
      --maxmemory-policy allkeys-lfu
      --maxclients 50000
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    deploy:
      resources:
        limits:
          memory: 256m
